name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_601GCBuEYCF6yXaEWmlsslQ5
          VERCEL_PROJECT_ID: prj_o5FDS7Fh9lRq5yoetgpz0WY9eOKe
